apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-2
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  volumes: []